### ISSUE TITLE
Make traefik to be aware of certificates

### ISSUE THREAD

**Issue by dgasull** [mF2C/mF2C#282]
Traefik mounts pkidata volume to find certificates, but certificates take some time to be ready and current traefik configuration is not able to find out that the certificates are there. 

Find a way to do it.

**Comment by cjdcordeiro** [comment]
@dgasull have you tried file watching?
```[file]
  watch = true
  directory = "/config/"```

**Comment by dgasull** [comment]
Yes I have :/

**Comment by dgasull** [comment]
After doing some research, I did not found a way to make traefik use a certificate added as a default certificate. 

Traefik official documentation says to use "file provider" to watch changes in **toml configuration files** (and only toml files!) 

[https://docs.traefik.io/v1.7/configuration/entrypoints/#tls](https://docs.traefik.io/v1.7/configuration/entrypoints/#tls)

Thus, I tried the following (fast test). I modifying the healthcheck in cau-client to create a dynamic-traefik.toml file if the certificate is present (the healthcheck is executed every N seconds, so I just added some bash code, I know it's not the way to do it) 

```
[[tls]]
  [tls.certificate]
     certFile = "/ssl/server.crt"
     keyFile  = "/ssl/server.key"
```

Doing this, traefik finds out that there is a new certificate and adds it to specified domain. 

``level=debug msg="Adding certificate for domain(s) 7138722c447cca2324e59f48763feac0cedc5298a857a17cca153b628dc7f7e"``

I don't know which domain is it (I guess is the one specified in the certificate?). 

However, since traefik did not find any certificate at startup it creates a new self-signed traefik cert, and this one is the one served on every connection to localhost (since the domain is not localhost). So, currently **we are only offering traefik self-signed certificates, not the ones generated by cau** 

One option could be to move and est to traefik 2.0 but this means to change all others components labels using traefik. And I am not sure if traefik 2.0 will allow you to watch dynamic certificates and set them as defaults. 

Finally, if we start mf2c with certificates already created and located in a certain position, traefik works perfectly well with them. 

This issue is not related to secure dataclay connection but secure all mf2c since certificates are currently not being used. I don't know what else to do, I am stopping here.

**Comment by dgasull** [comment]
Here it is the toml configuration I am using: 

```
defaultEntryPoints = ["http", "https"]
    
[entryPoints]
        [entryPoints.http]
        address = ":80"
            [entryPoints.http.redirect]
                entryPoint = "https"
        [entryPoints.https]
        address = ":443"
            [entryPoints.https.tls]

     #[entryPoints.https.tls.clientCA]
     #files = ["/ssl/fogca.pem"]
     #optional = false

     # For secure connection on frontend.local
     #[entryPoints.https.tls.defaultCertificate]
     #certFile = "/ssl/server.crt"
     #keyFile  = "/ssl/server.key"
     #watch = true

[docker]
watch = true
exposedByDefault = false

# Adding certificates directly to the entryPoint is still maintained but certificates 
# declared in this way cannot be managed dynamically. 
# It's recommended to use the file provider to declare certificates.
[file]
directory = "/ssl/"
watch = true
```

**Comment by cjdcordeiro** [comment]
if you can make it work with 2.0 then we'll upgrade and I'll change the labels

**Comment by syc17** [comment]
--- I don't know which domain is it
This is the first 64 chars of the agent’s device id.  This is the CN in the certificate DN

S

**Comment by dgasull** [comment]
Same problem in version 2 (traefik requires to watch changes in a dynamic configuration file), keeping version 1. Traefik does not allow to change default certificate once it is defined, if no default certificate is provided, auto-generates one.

We can try one last thing, @syc17  Since the certificate is added to the domain <deviceID>, can you modify the certificate to add "Certificate Subject Alt Name" with DNS name "proxy" (the same name of the traefik service in docker-compose)?? 

Doing that maybe components will be able to use the proper certificates instead of the one auto- generated by traefik (which is a problem for all components now)

**Comment by dgasull** [comment]
If that works, we will need to add the dynamic configuration in cau-client once the certificate is visible. Just for you to know how I am doing this @syc17  (If a toml file appears in pkidata volume, traefik adds it to the domain specified in the certificate)

```
 cau-client:
     image: mf2c/cau-client-it2:v2.1
     volumes:
       - pkidata:/pkidata
      # ==== ADDED FOR TRAEFIK ====
       - ./docker-compose/traefik/dynamic_conf.toml:/dynamic_conf.toml
     depends_on:
       - policies
     expose:
       - 46065
     #using the cloud cau for the moment
     environment:
       - CCAU_URL=213.205.14.13:55443
       - CAU_URL=213.205.14.13:55443
     healthcheck:
       start_period: 60s
       interval: 60s
       timeout: 60s
       retries: 5
      # ==== ADDED FOR TRAEFIK ====
       test: ["CMD-SHELL", "echo getpubkey=1233211234567 | nc localhost 46065 && if [ -f /pkidata/server.crt ]; then cp /dynamic_conf.toml /pkidata/; fi"]

```
